name: hello-world # the name of your workflow in the workflow panel

on: 
  schedule:
    - cron: '* * * 1 *'
  push: # trigger for workflow, here it is for any push made to the main branch
    branches:
      - main
  workflow_dispatch: # THIS ENABLES MANUAL RUNS, GREAT TO INCLUDE FOR TROUBLESHOOTING :)

jobs:
  job1_with_secret:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SS_TOKEN }}

      - name: Set up Miniconda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yaml
          activate-environment: hello-env
          auto-activate-base: false

      - name: Run App
        run: |
          python app.py --txt

      - name: Commit and Push Changes 
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output.txt
          git commit -m "Append Hello World with timestamp to output.txt" || echo "No changes to commit"
          git push
